
services:
  db:
    image: postgres:15
    container_name: ${CONTAINER_NAME}_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  fastapi:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: ${CONTAINER_NAME}_fastapi
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

    cpus: "1.0"
    mem_limit: 512m

    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  data_gathering:
    build:
      context: .
      dockerfile: DataGathering/Dockerfile
    container_name: ${CONTAINER_NAME}_data
    restart: "on-failure"
    env_file:
      - .env
    depends_on:
      - fastapi
    networks:
      - app-network

  pushgateway:
    image: prom/pushgateway:latest
    container_name: ${CONTAINER_NAME}_pushgateway
    restart: always
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: ${CONTAINER_NAME}_prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    container_name: ${CONTAINER_NAME}_grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: backend_api_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi
    networks:
      - app-network

volumes:
  postgres_data:
  grafana_data:

networks:
  app-network:
    driver: bridge
