{
 "title": "Data Pipeline Overview",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "provider",
    "label": "Provider",
    "query": {
     "query": "label_values(dg_provider_status, provider)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Data Gathering", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Provider status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dg_provider_status{provider=~\"$provider\"}",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Time passed from last Provider run",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - dg_provider_last_run_timestamp{provider=~\"$provider\"}",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  { "title": "Data Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Processed times",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (provider) (increase(dp_ops_total{status=\"success\", provider=~\"$provider\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing failed times",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (provider) (increase(dp_ops_total{status=\"error\", provider=~\"$provider\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg processing time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dp_processing_duration_seconds_sum{provider=~\"$provider\"} / dp_processing_duration_seconds_count{provider=~\"$provider\"}",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Processed rows saved",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (provider) (increase(dp_saved_rows_total{provider=~\"$provider\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time passed from last Processing",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - dp_last_success_timestamp{provider=~\"$provider\"}",
     "legendFormat": "{{provider}}"
    }
   ]
  }
 ]
}