"""Move params from provider to run

Revision ID: 1ae9bb194cfa
Revises: 32f7fad260c5
Create Date: 2025-11-22 09:09:07.632483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae9bb194cfa'
down_revision: Union[str, Sequence[str], None] = '32f7fad260c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_provider_unique'), 'provider', schema='raw_data', type_='unique')
    op.create_unique_constraint('uq_provider_unique', 'provider', ['name', 'endpoint'], schema='raw_data')
    op.drop_column('provider', 'params', schema='raw_data')
    op.add_column('run', sa.Column('params', sa.Text(), nullable=True), schema='raw_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'params', schema='raw_data')
    op.add_column('provider', sa.Column('params', sa.TEXT(), autoincrement=False, nullable=True), schema='raw_data')
    op.drop_constraint('uq_provider_unique', 'provider', schema='raw_data', type_='unique')
    op.create_unique_constraint(op.f('uq_provider_unique'), 'provider', ['name', 'endpoint', 'params'], schema='raw_data', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
