"""unique constraint

Revision ID: 32f7fad260c5
Revises: e2de55905706
Create Date: 2025-11-16 09:45:04.761009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f7fad260c5'
down_revision: Union[str, Sequence[str], None] = 'e2de55905706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_provider_unique', 'provider', ['name', 'endpoint', 'params'], schema='raw_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_provider_unique', 'provider', schema='raw_data', type_='unique')
    # ### end Alembic commands ###
