"""add column to raw data file format

Revision ID: 59fa246eed38
Revises: d188bde57334
Create Date: 2026-03-07 12:15:15.990263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fa246eed38'
down_revision: Union[str, Sequence[str], None] = 'd188bde57334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_data', sa.Column('data_format', sa.Text(), nullable=False, server_default="json"), schema='raw_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_data', 'data_format', schema='raw_data')
    # ### end Alembic commands #d##