"""Add performance indexes for ML model queries

Revision ID: 7702d31d54bb
Revises: 59fa246eed38
Create Date: 2026-03-21 12:41:53.120254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7702d31d54bb'
down_revision: Union[str, Sequence[str], None] = '59fa246eed38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_run_provider_status_time_desc', 'run', ['provider_id', 'status', 'run_timestamp'], unique=False, schema='core', postgresql_ops={'run_timestamp': 'DESC'})
    op.create_index('idx_processed_data_run_id', 'processed_data', ['run_id'], unique=False, schema='processed_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_processed_data_run_id', table_name='processed_data', schema='processed_data')
    op.drop_index('idx_run_provider_status_time_desc', table_name='run', schema='core', postgresql_ops={'run_timestamp': 'DESC'})
    # ### end Alembic commands ###