"""initial migration

Revision ID: e2de55905706
Revises: 
Create Date: 2025-10-28 19:36:15.885396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2de55905706'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='raw_data'
    )
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['raw_data.provider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='raw_data'
    )
    op.create_table('raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['raw_data.run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='raw_data'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_data', schema='raw_data')
    op.drop_table('run', schema='raw_data')
    op.drop_table('provider', schema='raw_data')
    # ### end Alembic commands ###
